connectedin/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('core.urls')),
    url(r'', include('contas.urls')),
    url(r'', include('feed.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

contas/urls.py
from django.conf.urls import url
from django.contrib.auth import views
from .views import *

urlpatterns = [
    url(r'^cadastrar/$', ViewCadastrarUsuario.as_view(), name="cadastrar"),
    url(r'^Esquecer/$', ViewEsquecerSenhaVerification.as_view(), name="esqueci_senha"),
    url(r'^Esquecer/(?P<token>.+)$', ViewDefinirNovaSenha.as_view(), name="nova_senha"),
    url(r'^cadastrar/$', ViewCadastrarUsuario.as_view(), name="cadastrar"),
    url(r'^login/$', views.LoginView.as_view(template_name="login.html"), name='login'),
    url(r'^logout/$', views.LogoutView.as_view(template_name="login.html"), name='logout'),
    url(r'^password/$', mudarSenha, name='mudarSenha'),
]

core/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name="index"),
    url(r'^profile/(?P<id>\d+)/$', views.show_profile, name="show_profile"),
    url(r'^profile/(?P<id>\d+)/invite$', views.invite_profile, name="invite_profile"),
    url(r'^profile/(?P<id>\d+)/delete', views.remove_profile, name="remove_profile"),
    url(r'^profile/(?P<id>\d+)/deactivate', views.deactivate_profile, name="deactivate_profile"),
    url(r'^profile/(?P<id>\d+)/superuser', views.toggle_superuser, name="toggle_superuser"),
    url(r'^profile/(?P<invite_id>\d+)/accept$', views.invite_accept, name="invite_accept"),
    url(r'^profile/(?P<invite_id>\d+)/decline$', views.invite_decline, name="invite_decline"),
    url(r'^profile/blocks', views.blocks, name="blocks"),
    url(r'^profile/(?P<id>\d+)/block', views.block, name="block"),
    url(r'^profile/(?P<id>\d+)/unblock', views.remove_block, name="unblock"),
    url(r'^convites$', views.view_convites, name="convites"),
    url(r'^friends$', views.view_friends, name="friends"),
    url(r'^friends/(?P<id>\d+)/remove$', views.remove_a_friend, name="remove_a_friend"),
]

contas/models.py
from django.db import models

# Create your models here.

contas/forms.py
from django import forms
from django.contrib.auth.models import User
from django.core.files.images import get_image_dimensions

from core.models import Profile


class FormEsquecerSenhaVerification(forms.Form):

    email = forms.EmailField(required=True)
    security_question = forms.ChoiceField(choices=Profile.DEFAULT_QUESTIONS, required=True)
    security_answer = forms.CharField(max_length=64, required=True)

    def is_valid_from_form(self):
        return super(FormEsquecerSenhaVerification, self).is_valid()

    def is_valid(self):
        valid = self.is_valid_from_form()
        data = self.cleaned_data
        user_exists = User.objects.filter(email=data['email']).exists()
        if not user_exists:
            valid = user_exists
            self.add_error(field="email", error="Não há conta cadastrada com este e-mail")
        else:
            user = User.objects.get(email=data['email'])
            profile = Profile.objects.get(user=user)
            valid_security = profile.verify_security(
                security_question=data['security_question'],
                security_answer=data['security_answer']
            )
            if valid_security:
                valid = valid_security
            else:
                self.add_error(field=forms.ALL_FIELDS, error="Tente novamente")
        return valid


class FormDefinirNovaSenha(forms.Form):

    email = forms.EmailField(required=True)
    new_Senha1 = forms.PasswordInput()
    new_Senha2 = forms.PasswordInput()

    def is_valid_from_form(self):
        return super(FormDefinirNovaSenha, self).is_valid()

    def is_valid(self):
        valid = self.is_valid_from_form()
        data = self.data
        valid_Senha = data['new_Senha1'] == data['new_Senha2']
        user_exists = User.objects.filter(email=data['email']).exists()
        if not user_exists:
            valid = False
            self.add_error(field="email", error="Não há conta registrada com este e-mail")
        if not valid_Senha:
            valid = False
            self.add_error(field=forms.ALL_FIELDS, error="As senhas não conferem")
        return valid


class FormCadastrarUsuario(forms.Form):

    name = forms.CharField(max_length=64, required=True)
    email = forms.EmailField(required=True)
    Senha = forms.PasswordInput()
    phone = forms.CharField(max_length=12, required=True)
    business = forms.CharField(max_length=32, required=True)
    security_question = forms.ChoiceField(choices=Profile.DEFAULT_QUESTIONS, required=True)
    security_answer = forms.CharField(max_length=64, required=True)

    def is_valid_from_form(self):
        return super(FormCadastrarUsuario, self).is_valid()

    def is_valid(self):
        valid = self.is_valid_from_form()
        user_exists = User.objects.filter(email=self.cleaned_data['email']).exists()
        if user_exists:
            valid = not user_exists
            self.add_error(field="email", error="Já existe uma conta com este e-mail")
        return valid

contas/views.py
from datetime import datetime, timedelta

from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.forms import PasswordChangeForm
from django.shortcuts import render, redirect
from django.views.generic.base import View

from contas.forms import *
from core.models import Token


class ViewCadastrarUsuario(View):

    template = 'cadastrar.html'

    def get(self, request, *args, **kwargs):
        form = FormCadastrarUsuario()
        return render(request, self.template, {'form': form})

    def post(self, request, *args, **kwargs):
        form = FormCadastrarUsuario(request.POST, request.FILES)
        if form.is_valid():
            data = form.data
            user = User.objects.create_user(username=data['name'].replace(" ", "_").lower(), email=data['email'], password=data['password'])
            profile = Profile.objects.create(
                name=data['name'],
                phone=data['phone'],
                business=data['business'],
                security_question=data['security_question'],
                security_answer=data['security_answer'],
                user=user)
            profile.save()
            return redirect('login')
        return render(request, self.template, {'form': form})


class ViewEsquecerSenhaVerification(View):

    template = 'esqueci_senha_verif.html'

    def get(self, request, *args, **kwargs):
        form = FormEsquecerSenhaVerification()
        return render(request, self.template, {'form': form})

    def post(self, request, *args, **kwargs):
        form = FormEsquecerSenhaVerification(request.POST)
        if form.is_valid():
            date_until = datetime.now() + timedelta(minutes=10)
            token = Token.objects.create(until=date_until)
            return redirect('nova_senha', token=token.uuid)
        else:
            return render(request, self.template, {'form': form})


class ViewDefinirNovaSenha(View):

    template = 'DefinirNovaSenha.html'

    def get(self, request, *args, **kwargs):
        form = FormDefinirNovaSenha()
        uuid = kwargs['token']
        token = Token.objects.get(uuid=uuid)
        print("Refused password renewal with token ", token)
        if token.is_valid():
            return render(request, self.template, {'form': form})
        else:
            return redirect('esqueci_senha')

    def post(self, request, *args, **kwargs):
        form = FormDefinirNovaSenha(request.POST)
        if form.is_valid():
            data = form.data
            user = User.objects.get(email=data['email'])
            user.set_password(data['nova_senha2'])
            user.save()
            update_session_auth_hash(request, user)
            return redirect('login')
        else:
            return render(request, self.template, {'form': form})

def mudarSenha(request):
    if request.method == 'POST':
        form = PasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            user = form.save()
            update_session_auth_hash(request, user)
            return redirect('index')
        else:
            return render(request, 'mudarSenha.html', {'form': form})
    else:
        form = PasswordChangeForm(request.user)
    return render(request, 'mudarSenha.html', {'form': form})

contas/templates/DefinirNovaSenha.html
{% extends 'user_default.html' %}

{% block extra-title %} - Change your senha {% endblock %}

{% block content %}

<form class="form-signin" method="post" role="form">
  {% csrf_token %}

  <div class="form-group">
      <label for="id_email">E-mail</label>
      <input type="email" id="id_email" name="email" class="form-control" placeholder="nome@dominio.com" required autofocus>
  </div>

  <label for="id_nova_senha1">Sua nova senha</label>
  <input type="senha" id="id_nova_senha1" name="nova_senha1" class="form-control" placeholder="********" required>

  <br>

  <label for="id_nova_senha2">Verifique sua nova senha</label>
  <input type="senha" id="id_nova_senha2" name="nova_senha2" class="form-control" placeholder="********" required>
  <hr/>

  <button class="btn btn-lg btn-primary btn-block" type="submit">Salvar alterações</button>

  <hr/>

  {% if form.errors %}
    <div class="alert alert-danger">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
      {{ form.errors }}
    </div>
    <hr/>
  {% endif %}

</form>


{% endblock %}

contas/templates/cadastrar.html
{% extends 'user_default.html' %}


{% block content %}

<form class="form-signin" action="{% url 'cadastrar' %}" method="post" enctype="multipart/form-data">

    {% csrf_token %}

    <div class="form-group">
        <label for="field_email">E-mail</label>
        <input type="email" id="field_email" name="email" class="form-control" placeholder="nome@dominio.com" required autofocus>
    </div>

    <div class="form-group">
        <label for="field_name">Nome</label>
        <input type="text" id="field_name" name="name" class="form-control" placeholder="Insira seu nome" required >
    </div>

    <div class="form-group">
        <label for="field_password">Senha</label>
        <input type="password" id="field_password" name="password" class="form-control" placeholder="********" required>
    </div>

    <hr />

    <div class="form-group">
        <label for="field_phone">Telefone</label>
        <input type="text" id="field_phone" name="phone" class="form-control" placeholder="(DDD) XXXX-XXXX">
    </div>
    <div class="form-group">
        <label for="field_business">Apelido</label>
        <input type="text" id="field_business" name="business" class="form-control" placeholder="Insira seu apelido">
    </div>

    <hr />

    <div class="form-group">
        <label for="id_security_question">Pergunta de segurança</label>
        <select name="security_question" class="form-control" id="id_security_question">
            <option value="1">Onde você mora?</option>
            <option value="2">Qual o seu apelido de colegial?</option>
            <option value="3">Qual o nome da(o) sua/seu primera(o) professora/professor? </option>
        </select>
    </div>

    <div class="form-group">
        <label for="id_security_answer">Resposta</label>
        <input type="text" name="security_answer" class="form-control" maxlength="64" required id="id_security_answer" />
    </div>

    <hr />

    {% if form.errors %}
    <div class="alert alert-danger">
    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
    {{ form.errors }}
    </div>
    <hr/>
    {% endif %}


    <button class="btn btn-lg btn-primary btn-block" type="submit" value="Submit">Enviar</button>
    <a href="../" class="btn btn-lg btn-danger btn-block" >Cancelar</a>



</form>

{% endblock %}

contas/templates/esqueci_senha_verif.html
{% extends 'user_default.html' %}

{% block extra-title %} - Esqueci a senha {% endblock %}

{% block content %}

<form class="form-signin" method="post" role="form">

  {% csrf_token %}

  <div class="form-group">
      <label for="id_email">E-mail</label>
      <input type="email" id="id_email" name="email" class="form-control" placeholder="example@email.com" required autofocus>
  </div>

  <div class="form-group">
        <label for="id_security_question">Questão de segurança</label>
        <select name="security_question" class="form-control" id="id_security_question">
            <option value="1">Onde você mora?</option>
            <option value="2">Qual o seu apelido de colegial?</option>
            <option value="3">Qual o nome da(o) sua/seu primera(o) professora/professor? </option>
        </select>
    </div>

    <div class="form-group">
        <label for="id_security_answer">Security answer</label>
        <input type="text" name="security_answer" class="form-control" maxlength="64" required id="id_security_answer" />
    </div>

    <hr />

    {% if form.errors %}
    <div class="alert alert-danger">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
        {{ form.errors }}
    </div>
    <hr/>
    {% endif %}

    <div class="well well-sm">Você será redirecionado... Aguarde!</div>


    <button class="btn btn-lg btn-primary btn-block" type="submit" value="Submit">Enviar</button>

</form>


{% endblock %}

contas/templates/login.html
{% extends "user_default.html" %}


{% block extra-title %} {% endblock %}

{% block content %}

    <form class="form-signin" role="form" action="{% url 'login' %}" method="post">
    {% csrf_token %}
        <input type="email" id="field_username" name="username" class="form-control" placeholder="nome@dominio.com" required autofocus>
        <hr/>
        <input type="password" id="field_password" name="password" class="form-control" placeholder="********" required>
        <hr/>
        <button class="btn btn-lg btn-primary btn-block" type="submit" value="Login">Login</button>
    {% if form.errors %}
        <hr/>
        <div class="alert alert-danger">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
        O e-mail ou senha não conferem...
        </div>
    {% endif %}

    </form>
        <a href="../" class="btn btn-lg btn-danger btn-block" >Voltar</a>


<button class="btn btn-sm btn-block btn-link"><a href="{% url 'esqueci_senha' %}">Esqueci a senha</a></button>


{% endblock %}

contas/templates/mudarSenha.html
{% extends 'user_default.html' %}

{% block extra-title %} - Mude sua senha {% endblock %}

{% block content %}

<form class="form-signin" method="post" role="form">
  {% csrf_token %}
  <!-- {{ form }} -->
  <label for="id_antiga_senha">Senha atual</label>
  <input type="senha" id="id_antiga_senha" name="antiga_senha" class="form-control" placehantigaer="********" required>
  <hr/>
  <label for="id_nova_senha1">Nova senha</label>
  <input type="senha" id="id_nova_senha1" name="nova_senha1" class="form-control" placehantigaer="********" required>
  <br>
  <label for="id_nova_senha2">Verifique sua nova senha</label>
  <input type="senha" id="id_nova_senha2" name="nova_senha2" class="form-control" placehantigaer="********" required>
  <hr/>
  <button class="btn btn-lg btn-primary btn-block" type="submit">Salvar alterações</button>
  {% if form.error_messages %}
      <hr/>
      <div class="alert alert-danger">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
      {% for error in form.error_messages.values %}
          <div class="well-sm">{{error}}</div>
      {% endfor %}
      </div>
  {% endif %}

</form>


{% endblock %}

contas/templates/user_default.html
{% load staticfiles %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width">
    <title>ConnectedIn</title>
    <link href="{% static 'styles/bootstrap.css' %}" rel="stylesheet"/>
    <link href="{% static 'styles/main.css' %}" rel="stylesheet"/>
</head>

<body>
<div class="container">
    <div class="header">
        <h5 class="text-center text-muted">ConnectedIn {% block extra-title %}{% endblock %}</h3>
    </div>
    {% block content %}
    {% endblock %}
 
</div>

<script src="{% static 'scripts/vendor/jquery-1.9.1.js' %}"></script>
<script src="{% static 'scripts/vendor/bootstrap-min.js' %}"></script>
<script>
    {% block js %}
    {% endblock %}
</script>

</body>
</html>